  <!-- Css Styles -->
  <link rel="stylesheet" href="/theme/client/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/elegant-icons.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/magnific-popup.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/nice-select.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/owl.carousel.min.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/slicknav.min.css" type="text/css">
  <link rel="stylesheet" href="/theme/client/css/style.css" type="text/css">